#!/bin/bash

TEMPLATE_FILE=${TEMPLATE_FILE:-"/var/log/loadmonitor/loadmonitor.template"}
HTML_FILE=${HTML_FILE:-"/var/log/loadmonitor/$(hostname).html"}
LOGS=$(cat /var/log/loadmonitor/*.tsv | zcat /var/log/loadmonitor/*.tsv*gz)

sed "s/%%%HOSTNAME%%%/$(hostname)/g" $TEMPLATE_FILE | \
sed "s/%%%LOADLOG%%%/${LOGS}/g" > $HTML_FILE

