#!/bin/bash

#
# CONFIGURACIÓN:
# Variables de entorno - valores por defecto
#
# Límite de carga puntual. Entero. Por defecto: el número de cores - 2
LIMIT_LOAD=${LIMIT_LOAD:-$(($(nproc) - 2))}
# Límite de porcentaje de uso de un punto de montaje. Entero. Por defecto: 90
LIMIT_DISK=${LIMIT_DISK:-90}
# Puntos de montaje a revisar
MOUNT_POINTS=${MOUNT_POINTS}
# Conexión a bot de telegram y sala destino
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
TELEGRAM_LANG=${TELEGRAM_LANG:-es}

# Constantes
LOG="/var/log/loadmonitor/$(hostname).tsv"
ADJUNTO="/tmp/$(hostname)-status.txt"
LOAD_RAISE="/tmp/serveralerts2telegram-load-raise"
DISK_RAISE="/tmp/serveralerts2telegram-disk-raise"

function write2telegram() {
  MENSAJE="$*"
  if [[ ! -z ${TELEGRAM_BOT_TOKEN} ]]
  then
    curl -s -F parse_mode=HTML \
     -F chat_id="${TELEGRAM_CHAT_ID}" -F document=@"${ADJUNTO}" -F caption="${MENSAJE}" \
     https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument?parse_mode=HTML
  fi
}

function translateLimitLoadUp() {
  if [[ "$TELEGRAM_LANG" == "en" ]]
  then
    echo "Load limit set to $1 have been raised. Now: $2. "
  else
    echo "Ha superado el límite de carga establecido a $1. Carga actual: $2. "
  fi
}

function translateLimitLoadDown() {
  if [[ "$TELEGRAM_LANG" == "en" ]]
  then
    echo "Load limit is under $1 again. Now: $2. "
  else
    echo "Vuelve a estar por debajo del límite de carga establecido a $1. Carga actual: $2. "
  fi
}

function translateLimitDiskUp() {
  if [[ "$TELEGRAM_LANG" == "en" ]]
  then
    echo "Disk $MOUNT_POINTS use limit set to $1% have been raised."
  else
    echo "Ha superado el límite de uso de disco $MOUNT_POINTS establecido a $1%."
  fi
}

function translateLimitDiskDown() {
  if [[ "$TELEGRAM_LANG" == "en" ]]
  then
    echo "Disk $MOUNT_POINTS use limit is under $1% again."
  else
    echo "Vuelve a estar por debajo del límite de uso de disco $MOUNT_POINTS establecido a $1%."
  fi
}

#
# VERIFICACIONES
#
[ "$(id -u)" != "0" ] && echo "ERR: This script must be run as root" && exit 1
[ -z ${TELEGRAM_BOT_TOKEN} ] && echo "ERR: TELEGRAM_BOT_TOKEN not defined" && exit 1
[ -z ${TELEGRAM_CHAT_ID} ] && echo "ERR: TELEGRAM_CHAT_ID not defined" && exit 1


UPTIME=$(uptime)
LOAD=$(echo "${UPTIME}" | grep -oE '[0-9]+[.,][0-9]+, [0-9]+[.,][0-9]+, [0-9]+[.,][0-9]+')
LOAD_TAB=$(echo "${LOAD}"  | sed 's/, /\t/g')
LOAD_PUNTUAL=$(echo "${LOAD}" | tr ',' '\n' | head -n 1)
DF=$(df -h --sync --total)
FILTRO_DF=$(echo "${MOUNT_POINTS}" | tr ' ' '|')
FILTRO_DF=$(echo "${DF}" | grep -E "${FILTRO_DF}" | grep -oE '[0-9]+%' | sed 's/%//g')
FECHA=$(date '+%Y-%m-%d %H:%M:%S')

# Guardamos log
[ -f "$LOG" ] && echo -e "${FECHA}\t$(hostname)\t${LOAD_TAB}" >> $LOG

# Comprobamos carga
MENSAJE_CARGA=""
if [[ "$LIMIT_LOAD" -le "$LOAD_PUNTUAL" ]];
then
  if [[ ! -f "$LOAD_RAISE" ]];
  then
    MENSAJE_CARGA=$(translateLimitLoadUp "$LIMIT_LOAD" "$LOAD")
    echo "$(date +%s)" > "$LOAD_RAISE"
  fi
else
  if [[ -f "$LOAD_RAISE" ]];
  then
    MENSAJE_CARGA=$(translateLimitLoadDown "$LIMIT_LOAD" "$LOAD")
    rm "$LOAD_RAISE"
  fi
fi

# Comprobamos uso de disco
MENSAJE_DISCO=""
for USO in $FILTRO_DF
do
  if [[ "$LIMIT_DISK" -le "$USO" ]];
  then
    MENSAJE_DISCO=$(translateLimitDiskUp "$LIMIT_DISK")
    [[ ! -f "$DISK_RAISE" ]] && echo "$(date +%s)" > "$DISK_RAISE"
    break
  fi
done

if [[ -f "$DISK_RAISE" ]];
then
  if [[ -z "$MENSAJE_DISCO" ]]
  then
    MENSAJE_DISCO=$(translateLimitDiskDown "$LIMIT_DISK")
    rm "$DISK_RAISE"
  else
    MENSAJE_DISCO=""
  fi
fi

MENSAJE="${MENSAJE_CARGA}${MENSAJE_DISCO}"
if [[ ! -z "$MENSAJE" ]];
then
  # Creamos archivo de ADJUNTO
  TOP=$(top -bn 1)
  IOTOP=$(iotop -botn 1)
  echo -e "UPTIME:\n$UPTIME\n\nDF:\n$DF\n\nIOTOP:\n$IOTOP\n\nTOP:\n$TOP\n" > $ADJUNTO
  # Enviamos mensaje por Telegram
  write2telegram "#$(hostname) $MENSAJE"
fi

